import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.className} antialiased`}
      >
        <div className="min-h-screen flex">
          <nav className="w-56 bg-teal-600 text-white flex flex-col items-center py-8">
            <div className="mb-8 text-2xl font-bold">Cartelera</div>
            <ul className="flex flex-col gap-4 w-full px-4">
              <li>
                <a href="/" className="block py-2 px-3 rounded hover:bg-zinc-800 transition">Inicio</a>
              </li>
              <li>
                <a href="/topMovies" className="block py-2 px-3 rounded hover:bg-zinc-800 transition">Top Movies</a>
              </li>
              <li>
                <a href="/administration" className="block py-2 px-3 rounded hover:bg-zinc-800 transition">Administration</a>
              </li>
            </ul>
          </nav>
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}